CREATE TABLE AUDIT_TABLE (
ID INT AUTO_INCREMENT,
USERNAME VARCHAR(255),
ACTION_TYPE VARCHAR(255),
USER_ROLE VARCHAR(255),
CREATED_TIMESTAMP TIMESTAMP,
USER_IP VARCHAR(255),
PRIMARY KEY (ID)
);